// components/Button.vue
<script lang="ts" setup>
    import External from '/components/icons/External.vue'
    import GitHub from './icons/GitHub.vue'
    import X from './icons/X.vue'
    import Dribbble from './icons/Dribbble.vue'
    import Email from './icons/Email.vue'
    import LinkedIn from './icons/LinkedIn.vue'

    const { href, preset = 'primary', icon } = defineProps<{
        href?: string
        preset?: 'primary' | 'secondary' | 'tertiary'
        icon?: 'external' | 'github' | 'x' | 'dribbble' | 'email' | 'linkedin'
        target?: string
    }>()

    const {
        Icon = undefined,
        iconClassName = '',
        iconRight = false,
    } = icon ? ({
        github: {
            Icon: GitHub,
            iconClassName: 'h-5'
        },
        x: {
            Icon: X,
            iconClassName: 'h-4'
        },
        linkedin: {
            Icon: LinkedIn,
            iconClassName: 'h-5'
        },
        email: {
            Icon: Email,
            iconClassName: 'h-4'
        },
        dribbble: {
            Icon: Dribbble,
            iconClassName: 'h-5'
        },
        external: {
            Icon: External,
            iconClassName: 'h-3',
            iconRight: true
        }
    } as const)[icon] : {}
</script>
<template>
    <component
        :is="href ? 'a' : 'button'"
        ref="button"
        :href
        :target
        :class="[
            'transition group isolate overflow-clip relative *:pointer-events-none leading-snug h-12 font-medium rounded-full flex items-center justify-center gap-3',
            target == '_blank' && icon !== 'external' && 'cursor-external',
            $slots.default
                ? 'px-7'
                : 'aspect-square',
            preset === 'primary'
                ? 'bg-black hover:bg-neutral-800 dark:bg-neutral-100 dark:hover:bg-white text-white dark:text-black'
                : preset === 'secondary'
                ? 'shadow-[inset_0_0_0_1px] shadow-black/20 hover:shadow-black/35 dark:shadow-white/45 dark:hover:shadow-white/65'
                : 'hover:bg-black/5 dark:hover:bg-white/20'
        ]"
    >
        <component :is="Icon" :class="iconClassName" v-if="!iconRight && Icon" />
        <span v-if="$slots.default" class="block relative overflow-hidden">
            <span class="block group-hover:-translate-y-[108%] group-hover:skew-y-6 transition">
                <slot />
            </span>
            <span aria-hidden="true" class="absolute top-full left-0 skew-y-6 group-hover:skew-y-0 group-hover:-translate-y-full transition">
                <slot />
            </span>
        </span>
        <component :is="Icon" :class="iconClassName" v-if="iconRight && Icon" />
    </component>
</template>

// src/components/Button.tsx
import External from '@/components/icons/External'
import GitHub from './icons/GitHub'
import X from './icons/X'
import Dribbble from './icons/Dribbble'
import Email from './icons/Email'
import LinkedIn from './icons/LinkedIn'
import { isExternal } from '@/utils/url'
import clsx from 'clsx'

const ICONS = {
	github: {
		Left: <GitHub className="h-5" />
	},
	x: {
		Left: <X className="h-4" />
	},
	linkedin: {
		Left: <LinkedIn className="h-5" />
	},
	email: {
		Left: <Email className="h-4" />
	},
	dribbble: {
		Left: <Dribbble className="h-5" />
	},
	external: {
		Right: <External className="h-3" />
	}
} as const

type Icon = keyof typeof ICONS

type Props = (JSX.IntrinsicElements['button'] | JSX.IntrinsicElements['a']) & {
	preset?: 'primary' | 'secondary' | 'tertiary'
	size?: 'sm' | 'md'
	icon?: Icon
}

export default function Button({
	className: _cls,
	preset = 'primary',
	size = 'md',
	children,
	icon,
	ref,
	...rest
}: Props) {
	const href = 'href' in rest ? rest.href : undefined
	const external = href && isExternal(href)
	const Icons = icon && ICONS[icon]

	const nodes = (
		<>
			{Icons && 'Left' in Icons && Icons.Left}
			{children}
			{Icons && 'Right' in Icons && Icons.Right}
		</>
	)

	const className = clsx(
		_cls,
		size === 'md' ? 'h-12' : 'h-8',
		'group relative isolate flex select-none items-center justify-center gap-3 overflow-clip rounded-full leading-snug transition ease-out-quad *:pointer-events-none',
		external && icon !== 'external' && 'cursor-external',
		children ?
			size === 'md' ?
				'px-7'
			:	'px-2.5 text-sm'
		:	'aspect-square',
		preset === 'primary' ?
			'bg-black font-medium text-white hover:bg-neutral-800 dark:bg-neutral-200 dark:text-black dark:hover:bg-white'
		:	['hover:bg-black/5 dark:hover:bg-white/10', preset === 'secondary' && 'ring-contrastier']
	)

	if ('href' in rest) {
		return (
			<a
				{...rest}
				className={className}
				href={href}
				rel={external ? 'external' : undefined}
				target={external ? '_blank' : undefined}
			>
				{nodes}
			</a>
		)
	}

	return (
		// @ts-expect-error weird type prop error
		<button {...rest} className={className}>
			{nodes}
		</button>
	)
}
