// src/components/Link.vue
<!-- Sets rel, target, and cursor for external links -->
<script lang="ts" setup>
import { useAttrs } from 'vue'
import { isExternal } from '@/utils/url'
const attrs = useAttrs()

const external = typeof attrs.href === 'string' && isExternal(attrs.href)
</script>

<template>
	<a
		:rel="external ? 'external' : undefined"
		:target="external ? '_blank' : undefined"
		:class="{ 'cursor-external': external }"
	>
		<slot />
	</a>
</template>

// src/components/Link.tsx
import clsx from 'clsx/lite'
import { isExternal } from '@/utils/url'

export default function Link({ href, className, ...rest }: JSX.IntrinsicElements['a']) {
	const external = typeof href === 'string' && isExternal(href)
	return (
		<a
			{...rest}
			rel={external ? 'external' : undefined}
			target={external ? '_blank' : undefined}
			className={clsx('cursor-external', className)}
		/>
	)
}
