// src/components/Video.vue
<script setup lang="ts">
import type { ImageMetadata } from 'astro'
import { onUnmounted, ref } from 'vue'
import { useElementVisibility, useEventListener } from '@vueuse/core'
import useTransitioning from '@/composables/useTransitioning'
import Spinner from '@/components/Spinner.vue'

const {
	class: className,
	forcePlay = false,
	spinner = true,
	src,
	muted = true,
	loop = true,
	autoplay = true,
	playsinline = true,
	poster,
	position = 'relative'
} = defineProps<{
	class?: string
	forcePlay?: boolean
	muted?: boolean
	playsinline?: boolean
	loop?: boolean
	autoplay?: boolean
	spinner?: boolean
	src: Array<{ file: string; type: string }>
	poster: ImageMetadata
	position?: string
}>()

const el = ref<HTMLDivElement>()
const video = ref<HTMLVideoElement>()
const inView = useElementVisibility(el)
const transitioning = useTransitioning()
const waiting = ref(false)
let waitingTimeout: NodeJS.Timeout
useEventListener(video, ['waiting', 'loadstart'], () => {
	if (waitingTimeout) clearTimeout(waitingTimeout)
	waitingTimeout = setTimeout(() => (waiting.value = true), 100)
})
useEventListener(video, ['playing', 'loadeddata'], () => {
	if (waitingTimeout) clearTimeout(waitingTimeout)
	waiting.value = false
})
onUnmounted(() => {
	if (waitingTimeout) clearTimeout(waitingTimeout)
})
</script>
<template>
	<div
		ref="el"
		:class="[className, position]"
		:style="{ aspectRatio: poster.width / poster.height }"
	>
		<video
			ref="video"
			:poster="poster.src"
			:muted
			:loop
			:playsinline
			:autoplay
			v-if="forcePlay || (!transitioning && inView)"
			class="size-full object-cover object-top"
		>
			<source v-for="{ file, type } in src" :src="file" :type="`video/${type}`" />
		</video>
		<img :src="poster.src" alt="" class="size-full object-cover object-top" v-else />
		<Spinner v-if="spinner && waiting && !transitioning" class="absolute bottom-4 left-4 size-7" />
		<slot />
	</div>
</template>

// src/components/Video.tsx
import clsx from 'clsx/lite'
import type { ImageMetadata } from 'astro'
import { useInViewport } from '@mantine/hooks'
import { $transitioning } from '@/stores/page'
import { useStore } from '@nanostores/react'
import Spinner from '@/components/Spinner'
import { useEffect, useRef, useState } from 'react'

export default function Video({
	className,
	forcePlay = false,
	spinner = true,
	src,
	muted = true,
	loop = true,
	autoPlay = true,
	playsInline = true,
	poster,
	position = 'relative',
	...props
}: Omit<JSX.IntrinsicElements['video'], 'src' | 'poster'> & {
	forcePlay?: boolean
	spinner?: boolean
	src: Array<{ file: string; type: string }>
	poster: ImageMetadata
	position?: string
}) {
	const { ref, inViewport } = useInViewport<HTMLDivElement>()
	const video = useRef<HTMLVideoElement>(null)
	const transitioning = useStore($transitioning)
	const [waiting, setWaiting] = useState(false)
	useEffect(() => {
		if (!video.current) return
		let waitingTimeout: NodeJS.Timeout
		const onVideoWaiting = () => {
			if (waitingTimeout) clearTimeout(waitingTimeout)
			waitingTimeout = setTimeout(() => setWaiting(true), 100)
		}
		const onVideoPlaying = () => {
			if (waitingTimeout) clearTimeout(waitingTimeout)
			setWaiting(false)
		}
		video.current.addEventListener('waiting', onVideoWaiting)
		video.current.addEventListener('loadstart', onVideoWaiting)
		video.current.addEventListener('playing', onVideoPlaying)
		video.current.addEventListener('loadeddata', onVideoPlaying)
		return () => {
			if (waitingTimeout) clearTimeout(waitingTimeout)
			if (!video.current) return
			video.current.removeEventListener('waiting', onVideoWaiting)
			video.current.removeEventListener('loadstart', onVideoWaiting)
			video.current.removeEventListener('playing', onVideoPlaying)
			video.current.removeEventListener('loadeddata', onVideoPlaying)
		}
	})
	return (
		<div
			ref={ref}
			className={clsx(className, position)}
			style={{ aspectRatio: poster.width / poster.height }}
		>
			{forcePlay || (!transitioning && inViewport) ?
				<video
					{...props}
					ref={video}
					poster={poster.src}
					muted={muted}
					loop={loop}
					playsInline={playsInline}
					autoPlay={autoPlay}
					className="size-full object-cover object-top"
				>
					{src.map(({ file, type }) => (
						<source src={file} type={`video/${type}`} />
					))}
				</video>
			:	<img src={poster.src} alt="" className="size-full object-cover object-top" />}
			{spinner && waiting && !transitioning && (
				<Spinner className="absolute bottom-4 left-4 size-7" />
			)}
			<slot />
		</div>
	)
}
